version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.3

parameters: 
  tf-version:
    default: 1.8.3
    type: string
  default-region:
    default: us-east-1
    type: string
  role-name:
    type: string
    default: "arn:aws:iam::730335471586:oidc-provider/oidc.circleci.com/org/5252cc30-103d-4668-8c6e-e0d0b434e734"

executors:
   tf-docker:
      docker: 
        - image: cimg/base:stable
      resource_class: medium
   tf-runner:
    machine: true
    resource_class: awesomecicd-standalone/machine-runner-ec2-us-east-1

jobs:
  tf-plan:
    executor: tf-docker
    steps:
      - checkout
      - aws-cli/setup:
          region: us-east-1
          role_arn: << pipeline.parameters.role-name >>
          role_session_name: "CircleCI-${CIRCLE_WORKFLOW_ID}-${CIRCLE_JOB}"
      - run: 
          name: test cli command 
          command: aws s3 ls



workflows:
    main:
      jobs:
        - tf-plan
