# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
version: 2.1
executors:
  machine-default:
    machine: true
    resource_class: cisco_sdwan/linux_ec2_test
    # environment:
    #   HTTPS_PROXY: "http://proxy.esl.cisco.com:80"
    #   NO_PROXY: "*.cisco.com"
jobs:
  vtest:
    executor: machine-default
    steps:
      - run:
          name: Clone vtest repository
          no_output_timeout: 3h
          command: |
            mkdir -p vtest
            git clone git@sdwan-git.cisco.com:sdwan/vtest.git vtest
      - run:
          name: vtest test suite
          no_output_timeout: 3h
          command: |
            cd vtest
            source /scratch/jenkins/venvs/py38_vtest/bin/activate
            bin/runner seat -t setup -t ux2_cfg_deploy_for_pr -ntr -ns -ntg -q -x -b next -a STABLE -y sdwan_init/viptela_vulcan_kvm -n CAT -o -c -n CAT -dvn -edvn stcvm -o -x -c -ns -b 20.15 --prefer-local-images --force-download-branch-images
  test:
    executor: machine-default
    steps:
      - run:
          name: Run tests
          command: echo "Hello. I am running as ${USER}"
  deploy:
    executor: machine-default
    steps:
      # Replace this with steps to deploy to users
      - run:
          name: deploy
          command: echo "Hello!"
workflows:
  example:
    jobs:
      - test
      - vtest:
          requires:
            - test
      - deploy:
          requires:
            - test
