# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
version: 2.1
jobs:
  test:
    machine: true
    resource_class: cisco_sdwan/linux_ec2_test
    steps:
      - checkout
      # Replace this with a real test runner invocation
      - run:
          name: Run tests
          command: echo "Hello!"
  build:
    machine: true
    resource_class: cisco_sdwan/linux_ec2_test
    steps:
      - checkout
      # Replace this with steps to build a package, or executable
      - run:
          name: Build an artifact
          command: echo "Hello!"
  deploy:
    machine: true
    resource_class: cisco_sdwan/linux_ec2_test
    steps:
      # Replace this with steps to deploy to users
      - run:
          name: deploy
          command: echo "Hello!"
workflows:
  example:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - test
